CREATE TABLE stations
(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uic_code VARCHAR(50) NOT NULL,
    medium_name VARCHAR(255) NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);