CREATE TABLE route_stations
(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    departure_id INT(10) UNSIGNED NOT NULL,
    uic_code VARCHAR(50) NOT NULL,
    medium_name VARCHAR(255) NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE route_stations ADD FOREIGN KEY (`departure_id`) REFERENCES departures(`id`);